services:
  opensearch-node:
    image: opensearchproject/opensearch:latest
    ports:
      - "9200:9200"
      - "9600:9600"
    environment:
      - "discovery.type=single-node"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Rikolti_05
