OAC - ['/select-oac-id']

UCD - ['/dpla_mapper?mapper_type=ucd_json']
NUX - ['/select-id?prop=uid']
ALX - ['/ucsb-aleph-marc-id']
OAI - ['/select-id?prop=id', '/select-oac-id', 'select-id?prop=id', '/select-id?prop=identifier']
SLR - ['/select-id?prop=id', '/select-id?prop=PID', 'select-id?prop=id']
PRE - ['/select-cmis-atom-id']
MRC - ['/sfpl-marc-id', '/csl-marc-id']
SFX - ['/dpla_mapper?mapper_type=ucsf_solr']
PRA - ['/select-id?prop=id', '/select-preservica-id']
UCB - ['/select-id?prop=id']
FLK - ['/select-id?prop=id']
YTB - ['/select-id?prop=id']
XML - ['/select-id?prop=metadata/identifier']
EMS - ['/select-id?prop=metadata/identifier']
IAR - ['/select-id?prop=identifier']