name: Add PRs to Rikolti MVP Project

on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled

jobs:
  add-to-project:
    name: Add PR to Rikolti post-MVP Project
    runs-on: ubuntu-latest
    steps:
      - name: Add To GitHub projects
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/ucldc/projects/2
          github-token: ${{ secrets.AMY_ADD_TO_PROJECT_TOKEN }}
        id: add-project
      - name: Update Project Fields
        uses: titoportas/update-project-fields@v0.1.0
        with:
          project-url: https://github.com/orgs/ucldc/projects/2
          github-token: ${{ secrets.AMY_ADD_TO_PROJECT_TOKEN }}
          item-id: ${{ steps.add-project.outputs.itemId }}
          field-keys: Status
          field-values: Up Next

                  

